"""a

Revision ID: 932ec9c5eefb
Revises: 
Create Date: 2023-01-06 21:01:54.714735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932ec9c5eefb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['uploader'], ['username'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_files', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('files_uploaded', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('files_uploaded')
        batch_op.drop_column('max_files')

    with op.batch_alter_table('csv_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uploader')

    # ### end Alembic commands ###
